### ISSUE TITLE
Who's Online displays wrong age

### ISSUE THREAD

**Issue by laudenbachm** [elwynor/elwglob#1]
The who's online both during logon and via the command # shows the incorrect user age. 

With my user it shows the age as 95 when my correct age is 44. 
Test user with the real age of 17 shows age 98

![image](https://github.com/user-attachments/assets/221c2b4b-ec21-49ea-bb49-19d4e37d39e9)
![image](https://github.com/user-attachments/assets/ce620a42-7aad-4500-8b72-c4ee33dc5508)

Thank you for your help!

Mark

**Comment by laudenbachm** [comment]
The ages are all over the place. Doesn't seem to have a common difference. Meaning someone born in 1980 and a user born in 1981 doesn't show one year older. 

![image](https://github.com/user-attachments/assets/69eb14f7-e11d-4ed6-a68f-50c40ec02f6f)

**Comment by elwynor** [comment]
Issue related to differing character string representing the birthdate in old Worldgroup vs. V10. V10 was passing YYYYMMDD, while the other was parsing MM/DD/YY.  

Fixed in v3.42
