### ISSUE TITLE
Who's Online displays wrong age

### ISSUE THREAD

**Issue by laudenbachm** [elwynor/elwglob#2]
The wrong age people born before 2000 was fixed with version 3.4.2. However, it now displays 1 in front of anyone who was born 2000 and after. Example: Let's say you were born July 1st, 2000, it displays your age as 124. 

Thank you!

Mark

**Comment by elwynor** [comment]
Fixed in v3.43 - required a new way to handle the 4 digit year and masking, on both WG32/V10 it turns out. Tested it on both platforms with users both before and after 2000. today() has a 1980 base, so it was important to include that.
